### ISSUE TITLE
TODO for version 0.3.0

### ISSUE THREAD

**Issue by jakobnissen** [jakobnissen/LibDeflate.jl#2]
## Behaviour
- [x] Make interfaces in public functions consistent and generic between deflate / zlib / gzip
- [x] Review LibDeflateErrors. Do we need more fine grained errors for e.g. gzip?

## Tests
- [x] Implement CI
- [x] Get code coverage near 100%

## Docs
- [x] Review docpage
- [x] Review all docstrings

## Final touches
- [x] Create release notes
